# Generated by Django 5.0.8 on 2024-08-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogwebapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMIssuesHeader',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('MIssueNo', models.CharField(max_length=50)),
                ('MDate', models.CharField(max_length=50)),
                ('MDescription', models.CharField(max_length=50)),
                ('MComment', models.CharField(max_length=50)),
                ('Reference', models.CharField(max_length=50)),
                ('IssueNo', models.CharField(max_length=50)),
                ('Posted', models.IntegerField()),
                ('LastUser', models.CharField(max_length=50)),
                ('LastMaintained', models.CharField(max_length=50)),
                ('SubLocation', models.CharField(max_length=50)),
                ('Contractor', models.CharField(max_length=50)),
                ('MSite', models.CharField(max_length=50)),
                ('TicketNo', models.CharField(max_length=50)),
                ('IssueType', models.CharField(max_length=50)),
                ('UserDepartment', models.CharField(max_length=50)),
                ('SDUManager', models.CharField(max_length=50)),
                ('ProcurementManager', models.CharField(max_length=50)),
                ('CTO', models.CharField(max_length=50)),
                ('RequestedBy', models.CharField(max_length=50)),
                ('Destination', models.CharField(max_length=50)),
                ('DeliveryDate', models.CharField(max_length=50)),
                ('RequestedByTime', models.CharField(max_length=50)),
                ('SDUManagerTime', models.CharField(max_length=50)),
                ('ProcurementManagerTime', models.CharField(max_length=50)),
                ('PostedToInventoryTime', models.CharField(max_length=50)),
            ],
        ),
    ]
